%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.0023
  accelerometer_random_walk: 7.1174e-05
  gyroscope_noise_density: 0.0002
  gyroscope_random_walk: 8.9858e-07
  model: calibrated
  rostopic: /calypso/imu
  time_offset: 0.0
  update_rate: 50.0
